apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-ns-01
commonLabels:
  magi-app: app-test-01
commonAnnotations:
  magi-deploy-type: namespace
resources:
- ../../../../projects/app-test-01
images:
- name: app-test-01
  newName: https://test.app.com/app.com
  newTag: 0.0.0