apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
commonLabels:
  magi-app: app-test-01
commonAnnotations:
  magi-deploy-type: cluster
resources:
- ../../../../projects/app-test-01
images:
- name: app-test-01
  newName: docker.io/nginx
  newTag: 0.0.0