apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-01-prod-app-test-01
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/demo-01/prod/app-test-01
  prune: true
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: vars-prod-01